# Generated by Django 4.1 on 2022-09-18 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('titre', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, max_length=5000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('foto', models.ImageField(upload_to='image/')),
                ('categori', models.ManyToManyField(to='profil.kategori')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profil.profile')),
            ],
        ),
    ]
