# Generated by Django 4.1 on 2022-09-18 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projet',
            old_name='user',
            new_name='author',
        ),
    ]
