# Generated by Django 4.1 on 2022-09-18 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projet', '0003_alter_projet_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proje_yo', to=settings.AUTH_USER_MODEL),
        ),
    ]
