# Generated by Django 4.1 on 2022-09-18 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0002_rename_use_profile_user'),
        ('projet', '0004_alter_projet_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='categori',
            field=models.ManyToManyField(blank=True, to='profil.kategori'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='foto',
            field=models.ImageField(blank=True, upload_to='image/'),
        ),
    ]
