# Generated by Django 4.1 on 2022-09-23 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0007_alter_projet_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
