# Generated by Django 4.1 on 2022-09-23 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0002_rename_use_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
